### ISSUE TITLE
Source code (zip) points to the wrong URL

### ISSUE THREAD

**Issue by eugman** [sql-bi/Contoso-Data-Generator-V2-Data#2]
The readme in the Source code (zip) points to https://github.com/sql-bi/Contoso-Data-Generator-V2-Data/releases/tag/2.0.0 instead of https://github.com/sql-bi/Contoso-Data-Generator-V2/releases/tag/2.0.0

**Comment by marcosqlbi** [comment]
It's a side effect of the way GitHub works - we keep a separate repo for data ready-to-use but we cannot remove those two links that are added automatically.
